##### Import libaries

In [1]:
import numpy as np
import pandas as pd

##### Series

One-dimensional ndarray with axis labels

In [2]:
pd.Series([10,8,27,9,98]) # It returns both indexes and values

0    10
1     8
2    27
3     9
4    98
dtype: int64

In [3]:
s=pd.Series([3, 12, 27, 9, 98])

In [4]:
print(s)

0     3
1    12
2    27
3     9
4    98
dtype: int64

In [5]:
print(type(s))

<class 'pandas.core.series.Series'>

In [6]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
s.values

array([ 3, 12, 27,  9, 98], dtype=int64)

In [8]:
s.dtype

dtype('int64')

In [9]:
s.size

5

In [10]:
pd.Series([10, 8, 27, 9, 98],index=['g', 'h', 'n', 'm', 'i']) #We can specify indexes.

g    10
h     8
n    27
m     9
i    98
dtype: int64

In [11]:
g=pd.Series([10, 8, 27, 9, 98],index=['g', 'h', 'n', 'm', 'i']) #We can specify indexes.

In [12]:
print(g)

g    10
h     8
n    27
m     9
i    98
dtype: int64

In [13]:
g['h']

8

In [14]:
#Updating values
g['h']='GH'

In [15]:
print(g)

g    10
h    GH
n    27
m     9
i    98
dtype: object

##### Dataframes

A group of Pandas Series objects that share the same index

In [16]:
pd.DataFrame({'Name': ["Sun","Moon", "Aug"], 'Age': [10, 8, 98]}) #It can be created directly

   Name  Age
0   Sun   10
1  Moon    8
2   Aug   98

In [17]:
df=pd.DataFrame({'Name': ["Sun","Moon", "Aug"], 'Age': [10, 8, 98]}) #It can be created directly

In [18]:
df

   Name  Age
0   Sun   10
1  Moon    8
2   Aug   98

##### Creating, Reading and Writing

**Export dataset**

In [19]:
df=pd.read_csv('datasets/winemag-data-130k-v2.csv')

In [20]:
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [21]:
df=pd.read_csv('datasets/winemag-data-130k-v2.csv', index_col=0)

In [22]:
df.sample(10)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
112179,US,Marked by pronounced oak on the nose and entry...,Vintner Select,88,50.0,California,Sonoma County,Sonoma,Virginie Boone,@vboone,Pride Mountain 2014 Vintner Select Chardonnay ...,Chardonnay,Pride Mountain
19988,Germany,"On the dry side, this medium-bodied kabinett c...",Jean-Baptiste Kabinett,87,19.0,Rheinhessen,NaN,NaN,Joe Czerwinski,@JoeCz,Gunderloch 2006 Jean-Baptiste Kabinett Rieslin...,Riesling,Gunderloch
14990,US,"Restrained, rather savory aromas of dill, fenn...",Dry,88,16.0,New York,Finger Lakes,Finger Lakes,Anna Lee C. Iijima,NaN,Silver Thread 2011 Dry Riesling (Finger Lakes),Riesling,Silver Thread
55289,US,There is a nice cherry core and exotic spice a...,NaN,86,14.0,California,California,California Other,Matt Kettmann,@mattkettmann,Paris Valley Road Cellars 2012 Cabernet Sauvig...,Cabernet Sauvignon,Paris Valley Road Cellars
24268,Italy,Enhanced with tiny percentages of Merlot and C...,NaN,87,14.0,Tuscany,Chianti Classico,NaN,NaN,NaN,Straccali 2010 Chianti Classico,Sangiovese,Straccali
68852,US,"This is, by the producer's own admission, the ...",Collins Holystone Vineyard,86,58.0,California,St. Helena,Napa,Virginie Boone,@vboone,Benessere 2014 Collins Holystone Vineyard Agli...,Aglianico,Benessere
86718,US,"As good as any Père de Famille to date, this b...",Père de Famille,97,68.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Betz Family 2010 Père de Famille Cabernet Sauv...,Cabernet Sauvignon,Betz Family
15464,US,"Dark and viscous, this greets the nose with ex...",Vista Verde Vineyard,93,40.0,California,San Benito County,Central Coast,Matt Kettmann,@mattkettmann,Williams Selyem 2009 Vista Verde Vineyard Port...,Port,Williams Selyem
18668,Australia,Hugh Hamilton's top-of-the-line wine is the Je...,Jekyll & Hyde,92,48.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Hugh Hamilton 2007 Jekyll & Hyde Shiraz-Viogni...,Shiraz-Viognier,Hugh Hamilton
124348,US,All estate grown and stainless steel fermented...,Grenache,88,18.0,Oregon,Umpqua Valley,Southern Oregon,Paul Gregutt,@paulgwine,Abacela 2015 Grenache Rosé (Umpqua Valley),Rosé,Abacela

In [23]:
df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [24]:
df.head(7)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo

In [25]:
df.tail()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [26]:
df.tail(7)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
129964,France,"Initially quite muted, this wine slowly develo...",Domaine Saint-Rémy Herrenweg,90,NaN,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...,Gewürztraminer,Domaine Ehrhart
129965,France,"While it's rich, this beautiful dry wine also ...",Seppi Landmann Vallée Noble,90,28.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Rieflé-Landmann 2013 Seppi Landmann Va...,Pinot Gris,Domaine Rieflé-Landmann
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [27]:
print('The columns of the dataset are:', df.columns) #show the dataframe columns

The columns of the dataset are: Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

In [28]:
print('The shape of the dataframe is:', df.shape)    #shape of the dataframe

The shape of the dataframe is: (129971, 13)

In [29]:
df.ndim #It shows dimension of a dataframe

2

In [30]:
df.size #It shows size of a dataframe

1689623

In [31]:
df.nunique()

country                      43
description              119955
designation               37979
points                       21
price                       390
province                    425
region_1                   1229
region_2                     17
taster_name                  19
taster_twitter_handle        15
title                    118840
variety                     707
winery                    16757
dtype: int64

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  object
 1   description            129971 non-null  object
 2   designation            92506 non-null   object
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  object
 6   region_1               108724 non-null  object
 7   region_2               50511 non-null   object
 8   taster_name            103727 non-null  object
 9   taster_twitter_handle  98758 non-null   object
 10  title                  129971 non-null  object
 11  variety                129970 non-null  object
 12  winery                 129971 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 13.9+ MB

In [33]:
#df.rename(columns={'points': 'score'}, inplace=True)
df.rename(columns={'points': 'score'})

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

##### Data Types and Missing Values

In [34]:
df['points'].dtype

dtype('int64')

In [35]:
df.dtypes

country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

In [36]:
#df['points']=df['points'].astype('float64')
df['points'].astype('float64')

0         87.0
1         87.0
2         87.0
3         87.0
4         87.0
          ...
129966    90.0
129967    90.0
129968    90.0
129969    90.0
129970    90.0
Name: points, Length: 129971, dtype: float64

##### Missing Values

In [37]:
df.isnull()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,False,False,False,False,True,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,True,True,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,False,False,False,False,False,False,True,True,False,True,False,False,False
129967,False,False,True,False,False,False,False,False,False,False,False,False,False
129968,False,False,False,False,False,False,False,True,False,False,False,False,False
129969,False,False,True,False,False,False,False,True,False,False,False,False,False
129970,False,False,False,False,False,False,False,True,False,False,False,False,False

In [38]:
df.isnull().sum()

country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

In [39]:
df.isnull().sum()/df.shape[0]

country                  0.000485
description              0.000000
designation              0.288257
points                   0.000000
price                    0.069215
province                 0.000485
region_1                 0.163475
region_2                 0.611367
taster_name              0.201922
taster_twitter_handle    0.240154
title                    0.000000
variety                  0.000008
winery                   0.000000
dtype: float64

In [40]:
df['region_2'].fillna('Unknown')

0                   Unknown
1                   Unknown
2         Willamette Valley
3                   Unknown
4         Willamette Valley
                ...
129966              Unknown
129967         Oregon Other
129968              Unknown
129969              Unknown
129970              Unknown
Name: region_2, Length: 129971, dtype: object

In [41]:
df['taster_twitter_handle'].replace("@kerinokeefe", "@kerino")

0             @kerino
1          @vossroger
2         @paulgwine
3                 NaN
4         @paulgwine
             ...
129966            NaN
129967    @paulgwine
129968     @vossroger
129969     @vossroger
129970     @vossroger
Name: taster_twitter_handle, Length: 129971, dtype: object

##### Indexing, Selecting & Assigning

In [42]:
df['country']

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [43]:
df.country

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [44]:
df['country'][0]

'Italy'

In [45]:
df['country'][0:5]

0       Italy
1    Portugal
2          US
3          US
4          US
Name: country, dtype: object

In [46]:
df[['country', 'points']]

         country  points
0          Italy      87
1       Portugal      87
2             US      87
3             US      87
4             US      87
...          ...     ...
129966   Germany      90
129967        US      90
129968    France      90
129969    France      90
129970    France      90

[129971 rows x 2 columns]

In [47]:
df[['country', 'points']]['country']

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

##### Indexing in pandas

**Label-based selection**

In [48]:
df.loc[:, 'country']

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [49]:
df.loc[1, 'country']

'Portugal'

In [50]:
df.loc[1:5, 'country']

1    Portugal
2          US
3          US
4          US
5       Spain
Name: country, dtype: object

In [51]:
df.loc[[1, 7, 10], 'country']

1     Portugal
7       France
10          US
Name: country, dtype: object

In [52]:
df.loc[[1, 7, 10], 'country']

1     Portugal
7       France
10          US
Name: country, dtype: object

In [53]:
df.loc[[1, 7, 10], 'country': 'points']

,country,description,designation,points
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87
7,France,This dry and restrained wine offers spice in p...,NaN,87
10,US,"Soft, supple plum envelopes an oaky structure ...",Mountain Cuvée,87

In [54]:
df.loc[[1, 7, 10], ['country', 'points']]

     country  points
1   Portugal      87
7     France      87
10        US      87

In [55]:
print(df['points'].idxmax())

345

In [56]:
df.loc[df['points'].idxmax()]

country                                                          Australia
description              This wine contains some material over 100 year...
designation                                                           Rare
points                                                                 100
price                                                                350.0
province                                                          Victoria
region_1                                                        Rutherglen
region_2                                                               NaN
taster_name                                                 Joe Czerwinski
taster_twitter_handle                                               @JoeCz
title                    Chambers Rosewood Vineyards NV Rare Muscat (Ru...
variety                                                             Muscat
winery                                         Chambers Rosewood Vineyards
Name: 345, dtype: object

In [57]:
df.iloc[1:5, 0]

1    Portugal
2          US
3          US
4          US
Name: country, dtype: object

In [58]:
df.iloc[1:5, 0: 3]

,country,description,designation
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block

In [59]:
df.iloc[1:5, [0, 3]]

    country  points
1  Portugal      87
2        US      87
3        US      87
4        US      87

##### Manipulating the index

In [60]:
df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [61]:
df.index

Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       129961, 129962, 129963, 129964, 129965, 129966, 129967, 129968, 129969,
       129970],
      dtype='int64', length=129971)

In [62]:
df.set_index('title')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
title,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore),US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley),US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel),Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
Citation 2004 Pinot Noir (Oregon),US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Pinot Noir,Citation
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace),France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Gresser
Domaine Marcel Deiss 2012 Pinot Gris (Alsace),France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Pinot Gris,Domaine Marcel Deiss
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace),France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Schoffit

In [63]:
df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [64]:
df.set_index('title', inplace=True)

In [65]:
df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
title,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore),US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley),US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks

In [66]:
df.index

Index(['Nicosia 2013 Vulkà Bianco  (Etna)',
       'Quinta dos Avidagos 2011 Avidagos Red (Douro)',
       'Rainstorm 2013 Pinot Gris (Willamette Valley)',
       'St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)',
       'Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)',
       'Tandem 2011 Ars In Vitro Tempranillo-Merlot (Navarra)',
       'Terre di Giurfo 2013 Belsito Frappato (Vittoria)',
       'Trimbach 2012 Gewurztraminer (Alsace)',
       'Heinz Eifel 2013 Shine Gewürztraminer (Rheinhessen)',
       'Jean-Baptiste Adam 2012 Les Natures Pinot Gris (Alsace)',
       ...
       'COS 2013 Frappato (Sicilia)',
       'Cusumano 2012 Sàgana Tenuta San Giacomo Nero d'Avola (Sicilia)',
       'Dalton 2012 Oak Aged Cabernet Sauvignon (Galilee)',
       'Domaine Ehrhart 2013 Domaine Saint-Rémy Herrenweg Gewurztraminer (Alsace)',
       'Domaine Rieflé-Landmann 2013 Seppi Landmann Vallée Noble Pinot Gris (Alsace)',
       'Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel)',
       'Citation 2004 Pinot Noir (Oregon)',
       'Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)',
       'Domaine Marcel Deiss 2012 Pinot Gris (Alsace)',
       'Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)'],
      dtype='object', name='title', length=129971)

In [67]:
df.reset_index()

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
0,Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
1,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
2,Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
3,St. Julian 2013 Reserve Late Harvest Riesling ...,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
4,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,Citation 2004 Pinot Noir (Oregon),US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Pinot Noir,Citation
129968,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Gresser
129969,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Pinot Gris,Domaine Marcel Deiss
129970,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Schoffit

In [68]:
df.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
title,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore),US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley),US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks

In [69]:
df.reset_index(inplace=True)

In [70]:
df.head()

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
0,Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
1,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
2,Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
3,St. Julian 2013 Reserve Late Harvest Riesling ...,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
4,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks

##### Conditional selection

In [71]:
df['country']=='England'

0         False
1         False
2         False
3         False
4         False
          ...
129966    False
129967    False
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

In [72]:
df[df['country']=='England']

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
4073,Ridgeview Estate 2011 Blanc de Blancs Chardonn...,England,A mix of fruity notes immediately hit: white c...,Blanc de Blancs,90,46.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Ridgeview Estate
6700,Wiston Estate Winery 2010 Cuvée Brut Sparkling...,England,Crisp green apple flavors are immediately appa...,Cuvée Brut,91,40.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Wiston Estate Winery
9909,Nyetimber 2010 Blanc de Blancs Chardonnay (Eng...,England,"Touches of vanilla, cream and lovely hints of ...",Blanc de Blancs,95,70.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Nyetimber
22156,Chapel Down 2010 Three Graces Sparkling (England),England,Golden color and hints of oatmeal on the nose ...,Three Graces,91,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Chapel Down
22369,Nyetimber NV Rosé Sparkling (England),England,"Pure notes of red apple rise from the glass, p...",Rosé,94,65.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Nyetimber
...,...,...,...,...,...,...,...,...,...,...,...,...,...
124898,Gusbourne Estate 2011 Blanc de Blancs Chardonn...,England,Creaminess and stone are all that is signalled...,Blanc de Blancs,93,80.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Gusbourne Estate
124922,Bolney Wine Estate NV Bolney Bubbly White (Eng...,England,The nose tells of the crisp green freshness of...,Bolney Bubbly,89,45.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,White Blend,Bolney Wine Estate
124924,Camel Valley 2013 Cornwall Sparkling (England),England,There is a flinty touch of reduction on the no...,Cornwall,89,25.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Camel Valley
128098,Digby Fine English NV Leander Pink Sparkling (...,England,Creamy notes of tart red currant and crisp red...,Leander Pink,89,61.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Digby Fine English
128839,Ridgeview Estate 2013 Bloomsbury Sparkling (En...,England,"Creamy notes of Golden Pearmain apple, shortcr...",Bloomsbury,92,39.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Ridgeview Estate

In [73]:
df[df['country']=='England']['country']

4073      England
6700      England
9909      England
22156     England
22369     England
           ...
124898    England
124922    England
124924    England
128098    England
128839    England
Name: country, Length: 74, dtype: object

In [74]:
df[df['country']=='England'][['country', 'points']]

        country  points
4073    England      90
6700    England      91
9909    England      95
22156   England      91
22369   England      94
...         ...     ...
124898  England      93
124922  England      89
124924  England      89
128098  England      89
128839  England      92

[74 rows x 2 columns]

In [75]:
df[(df['country']=='England') & (df['points']>90)]

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
6700,Wiston Estate Winery 2010 Cuvée Brut Sparkling...,England,Crisp green apple flavors are immediately appa...,Cuvée Brut,91,40.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Wiston Estate Winery
9909,Nyetimber 2010 Blanc de Blancs Chardonnay (Eng...,England,"Touches of vanilla, cream and lovely hints of ...",Blanc de Blancs,95,70.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Nyetimber
22156,Chapel Down 2010 Three Graces Sparkling (England),England,Golden color and hints of oatmeal on the nose ...,Three Graces,91,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Chapel Down
22369,Nyetimber NV Rosé Sparkling (England),England,"Pure notes of red apple rise from the glass, p...",Rosé,94,65.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Nyetimber
27356,Gusbourne Estate 2013 Brut Rosé Pinot Noir (En...,England,Freshly cut peel of tart but ripe red apple en...,Brut Rosé,93,80.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Pinot Noir,Gusbourne Estate
27364,Camel Valley 2014 Rosé Brut Pinot Noir (England),England,Hints of tart redcurrant have a softenting cre...,Rosé Brut,92,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Pinot Noir,Camel Valley
27848,Ridgeview Estate 2013 Rosé de Noirs Sparkling ...,England,Tart strawberries and cream are spelled out jo...,Rosé de Noirs,92,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Ridgeview Estate
27872,Bolney Wine Estate 2010 Blanc de Blancs Chardo...,England,"Lively, crisp apple notes on the nose immediat...",Blanc de Blancs,91,52.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Bolney Wine Estate
45590,Bolney Wine Estate 2009 Blanc de Blancs Chardo...,England,"This has the crunchy, enticing freshness of th...",Blanc de Blancs,94,NaN,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Bolney Wine Estate
47731,Jenkyn Place Vineyard 2010 Brut Cuvée Sparklin...,England,"An abundance of apple flavors—green, golden an...",Brut Cuvée,91,75.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Jenkyn Place Vineyard
54131,Exton Park Vineyard NV Rosé Sparkling (England),England,Notions of tart redcurrant play on the nose wh...,Rosé,93,43.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Exton Park Vineyard
54133,Gusbourne Estate 2013 Brut Reserve Sparkling (...,England,A generously ripe touch of apricot hovers befo...,Brut Reserve,93,60.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Gusbourne Estate
54686,Hattingley Valley Wines 2013 Classic Cuvée Spa...,England,"Creamy apple, lemon shortbread and fresh citru...",Classic Cuvée,92,NaN,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Hattingley Valley Wines
56417,Hoffmann & Rathbone 2013 Classic Cuvée Sparkli...,England,Notes of apple immediately rise from the glass...,Classic Cuvée,91,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Hoffmann & Rathbone
56660,Wiston Estate Winery 2010 Cuvée Brut Sparkling...,England,Crisp green apple flavors are immediately appa...,Cuvée Brut,91,40.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Wiston Estate Winery
58496,Bolney Wine Estate 2014 Blanc de Blancs Brut C...,England,A touch of wet stone reaches the nose even bef...,Blanc de Blancs Brut,92,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Bolney Wine Estate
58747,Ridgeview Estate 2013 Blanc de Blancs Chardonn...,England,Scented freshness of lemon and apple hits the ...,Blanc de Blancs,91,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Ridgeview Estate
58752,Bolney Wine Estate 2010 Blanc de Blancs Chardo...,England,"Lively, crisp apple notes on the nose immediat...",Blanc de Blancs,91,52.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Bolney Wine Estate
59857,Ridgeview Estate NV Bloomsbury Brut Sparkling ...,England,This wine brims with fruit and freshness. A ho...,Bloomsbury Brut,92,27.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Ridgeview Estate
59863,Camel Valley 2014 Rosé Brut Pinot Noir (England),England,Hints of tart redcurrant have a softenting cre...,Rosé Brut,92,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Pinot Noir,Camel Valley
60002,Sugrue Pierre Ltd. 2010 The Trouble with Dream...,England,Beautifully delineated fruit constitues the no...,The Trouble with Dreams,95,80.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Sugrue Pierre Ltd.
60027,Chapel Down 2011 Three Graces Sparkling (England),England,A restrained but impressive notion of honeyed ...,Three Graces,95,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Chapel Down
70570,Bolney Wine Estate 2009 Blanc de Blancs Chardo...,England,"This has the crunchy, enticing freshness of th...",Blanc de Blancs,94,NaN,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Bolney Wine Estate
70579,Wiston Estate Winery 2011 Rosé Sparkling (Engl...,England,Both the fruit and the aromatic foliage of wil...,Rosé,94,44.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Wiston Estate Winery
70597,Hattingley Valley Wines 2010 Blanc de Blancs C...,England,"Gentle white blossom, white currant and Golden...",Blanc de Blancs,94,45.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Hattingley Valley Wines
72070,Bolney Wine Estate 2015 Blanc de Blancs Brut C...,England,"A fragrant, sherbety cloud of spring meadow an...",Blanc de Blancs Brut,91,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Bolney Wine Estate
72073,Hattingley Valley Wines 2014 Rosé Sparkling (E...,England,Redcurrant and cranberry freshness plays on th...,Rosé,91,65.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Hattingley Valley Wines
82255,Hush Heath Estate 2011 Balfour Brut Rosé Spark...,England,"Pink-graprefruit zest and fresh strawberry, ta...",Balfour Brut Rosé,92,60.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Hush Heath Estate
84240,Gusbourne Estate 2013 Blanc de Blancs Chardonn...,England,A restrained but pure note of lemon constitute...,Blanc de Blancs,94,80.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Gusbourne Estate
84241,Hoffmann & Rathbone 2011 Blanc de Blancs Chard...,England,A touch of blossom honey enriches the tart but...,Blanc de Blancs,94,56.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Hoffmann & Rathbone
90299,Ridgeview Estate 2014 Fitzrovia Rosé Sparkling...,England,Floral notes play about the tart berry fruit o...,Fitzrovia Rosé,91,35.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Ridgeview Estate
100683,Bolney Wine Estate 2014 Blanc de Blancs Brut C...,England,A touch of wet stone reaches the nose even bef...,Blanc de Blancs Brut,92,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Bolney Wine Estate
100696,Hush Heath Estate 2013 Balfour Brut Rosé Spark...,England,"Blossom honey, a touch of melon and fresh, fra...",Balfour Brut Rosé,92,45.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Hush Heath Estate
100872,Hattingley Valley Wines 2013 Rosé Sparkling (E...,England,Notions of tart red berries and lemon claim th...,Rosé,91,NaN,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Hattingley Valley Wines
100884,Chapel Down 2010 Three Graces Sparkling (England),England,Golden color and hints of oatmeal on the nose ...,Three Graces,91,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Chapel Down
103173,Wiston Estate Winery 2010 Blanc de Blancs Char...,England,Sophisticated aromas of Golden Pearmain apples...,Blanc de Blancs,94,49.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Wiston Estate Winery
103174,Ridgeview Estate 2009 South Ridge Cuvée Merret...,England,"A lifting mix of golden, ripe apple, chamomile...",South Ridge Cuvée Merret Brut,94,38.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Ridgeview Estate
104659,Bride Valley Vineyard 2013 Blanc de Blancs Spa...,England,The crisp nose conjures up shades of green: me...,Blanc de Blancs,91,75.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Bride Valley Vineyard
104668,Ridgeview Estate 2014 Bloomsbury Sparkling (En...,England,Green apple and greengage on the nose turn int...,Bloomsbury,91,35.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Ridgeview Estate
105523,Hattingley Valley Wines NV Classic Reserve Spa...,England,Smooth hints of apricot and vanilla immediatel...,Classic Reserve,92,45.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Hattingley Valley Wines
105542,Chapel Down NV Brut Sparkling (England),England,The purest notion of Golden Pearmain apples is...,Brut,92,40.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Chapel Down
112249,Nyetimber NV Classic Cuvée Sparkling (England),England,This is a class act. Fresh white breadcrumb an...,Classic Cuvée,93,55.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Nyetimber
112252,Exton Park Vineyard NV Blanc de Noirs Pinot No...,England,A touch of honey clings to appetizingly tart r...,Blanc de Noirs,93,43.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Pinot Noir,Exton Park Vineyard
112263,Bolney Wine Estate 2014 Cuvée Rosé Brut Pinot ...,England,A whiff of blossom clings to the appetizing hi...,Cuvée Rosé Brut,93,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Pinot Noir,Bolney Wine Estate
112264,Bride Valley Vineyard 2014 Brut Reserve Sparkl...,England,There is almost something of the sea breeze in...,Brut Reserve,93,75.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Bride Valley Vineyard
114449,Henners 2011 Brut Sparkling (England),England,A crisp green-apple note has an appetizing lac...,Brut,91,42.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Henners
115311,Wiston Estate Winery 2013 Cuvée Brut Sparkling...,England,A toasty touch of brioche joins ripe red and y...,Cuvée Brut,94,40.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Wiston Estate Winery
115312,Wiston Estate Winery 2014 Rosé Sparkling (Engl...,England,Evocative redcurrant notes play on the nose. T...,Rosé,94,44.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Wiston Estate Winery
115319,Bride Valley Vineyard 2014 Rosé Bella Sparklin...,England,Restrained notes of tart red berry and pink gr...,Rosé Bella,94,85.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Bride Valley Vineyard
115329,Exton Park Vineyard 2011 Blanc de Blancs Chard...,England,Fragrant overtones of acacia honey play alongs...,Blanc de Blancs,94,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Exton Park Vineyard
124898,Gusbourne Estate 2011 Blanc de Blancs Chardonn...,England,Creaminess and stone are all that is signalled...,Blanc de Blancs,93,80.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Gusbourne Estate
128839,Ridgeview Estate 2013 Bloomsbury Sparkling (En...,England,"Creamy notes of Golden Pearmain apple, shortcr...",Bloomsbury,92,39.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Ridgeview Estate

and(&)-> both conditional need to be True

In [76]:
df[(df['country']=='England') & (df['points']>90)][['country', 'points']]

        country  points
6700    England      91
9909    England      95
22156   England      91
22369   England      94
27356   England      93
27364   England      92
27848   England      92
27872   England      91
45590   England      94
47731   England      91
54131   England      93
54133   England      93
54686   England      92
56417   England      91
56660   England      91
58496   England      92
58747   England      91
58752   England      91
59857   England      92
59863   England      92
60002   England      95
60027   England      95
70570   England      94
70579   England      94
70597   England      94
72070   England      91
72073   England      91
82255   England      92
84240   England      94
84241   England      94
90299   England      91
100683  England      92
100696  England      92
100872  England      91
100884  England      91
103173  England      94
103174  England      94
104659  England      91
104668  England      91
105523  England      92
105542  England      92
112249  England      93
112252  England      93
112263  England      93
112264  England      93
114449  England      91
115311  England      94
115312  England      94
115319  England      94
115329  England      94
124898  England      93
128839  England      92

or(|)-> either conditional is True

In [77]:
df[(df['country']=='England') | (df['points']>90)]

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
119,Dopff & Irion 2004 Schoenenbourg Grand Cru Ven...,France,Medium-gold in color. Complex and inviting nos...,Schoenenbourg Grand Cru Vendanges Tardives,92,80.0,Alsace,Alsace,NaN,NaN,NaN,Riesling,Dopff & Irion
120,Ceretto 2003 Bricco Rocche Prapó (Barolo),Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Nebbiolo,Ceretto
121,Matrix 2007 Stuhlmuller Vineyard Chardonnay (A...,US,The vineyard is one of the better Chardonnay s...,Stuhlmuller Vineyard,92,36.0,California,Alexander Valley,Sonoma,NaN,NaN,Chardonnay,Matrix
122,Mauritson 2007 Rockpile Cemetary Vineyard Zinf...,US,Defines Rockpile Zinfandel in intensity of fru...,Rockpile Cemetary Vineyard,92,39.0,California,Rockpile,Sonoma,NaN,NaN,Zinfandel,Mauritson
123,Henry's Drive Vignerons 2006 Parson's Flat Shi...,Australia,The blend is roughly two-thirds Shiraz and one...,Parson's Flat,92,40.0,South Australia,Padthaway,NaN,Joe Czerwinski,@JoeCz,Shiraz-Cabernet Sauvignon,Henry's Drive Vignerons
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129936,Bouchard Père & Fils 2005 Premier Cru (Pommard),France,A blend from several premier cru vineyards in ...,Premier Cru,91,66.0,Burgundy,Pommard,NaN,Roger Voss,@vossroger,Pinot Noir,Bouchard Père & Fils
129937,Bründlmayer 2007 Langenloiser Berg-Vogelsang G...,Austria,"Smooth, creamy aromas are followed by a rich, ...",Langenloiser Berg-Vogelsang,91,32.0,Kamptal,NaN,NaN,Roger Voss,@vossroger,Grüner Veltliner,Bründlmayer
129938,Chakana 2006 Reserve Malbec (Luján de Cuyo),Argentina,Compared to the regular 2006 Malbec from Chaka...,Reserve,91,25.0,Mendoza Province,Luján de Cuyo,NaN,Michael Schachner,@wineschach,Malbec,Chakana
129939,Schloss Halbturn 2004 Grand Vin White (Burgenl...,Austria,"A true TBA, its very rich, toffee-flavored, in...",Grand Vin,91,70.0,Burgenland,NaN,NaN,Roger Voss,@vossroger,White Blend,Schloss Halbturn
129940,Standish 2006 Watson Vineyard Chardonnay (Mend...,US,This is the winery's bells and whistles Chardo...,Watson Vineyard,91,36.0,California,Mendocino,NaN,NaN,NaN,Chardonnay,Standish

In [78]:
df[df['country'].isin(['England', 'Ukraine'])]

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
4073,Ridgeview Estate 2011 Blanc de Blancs Chardonn...,England,A mix of fruity notes immediately hit: white c...,Blanc de Blancs,90,46.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Ridgeview Estate
6700,Wiston Estate Winery 2010 Cuvée Brut Sparkling...,England,Crisp green apple flavors are immediately appa...,Cuvée Brut,91,40.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Wiston Estate Winery
9909,Nyetimber 2010 Blanc de Blancs Chardonnay (Eng...,England,"Touches of vanilla, cream and lovely hints of ...",Blanc de Blancs,95,70.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Chardonnay,Nyetimber
19530,Marengo NV Brut Sparkling (Ukraine),Ukraine,"On the nose, this nonvintage sparkler from the...",Brut,83,10.0,Ukraine,NaN,NaN,Jeff Jenssen,@worldwineguys,Sparkling Blend,Marengo
22156,Chapel Down 2010 Three Graces Sparkling (England),England,Golden color and hints of oatmeal on the nose ...,Three Graces,91,50.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Chapel Down
...,...,...,...,...,...,...,...,...,...,...,...,...,...
124924,Camel Valley 2013 Cornwall Sparkling (England),England,There is a flinty touch of reduction on the no...,Cornwall,89,25.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Camel Valley
126862,Côtnar Hills 2014 Merlot (Ukraine),Ukraine,This wine has aromas of pomegranate juice and ...,NaN,84,6.0,Ukraine,NaN,NaN,Jeff Jenssen,@worldwineguys,Merlot,Côtnar Hills
128098,Digby Fine English NV Leander Pink Sparkling (...,England,Creamy notes of tart red currant and crisp red...,Leander Pink,89,61.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Digby Fine English
128839,Ridgeview Estate 2013 Bloomsbury Sparkling (En...,England,"Creamy notes of Golden Pearmain apple, shortcr...",Bloomsbury,92,39.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Sparkling Blend,Ridgeview Estate
129621,Artemovsk 2008 KrimSekt White Collection Semi-...,Ukraine,Fresh apple notes on the nose of this off-dry ...,KrimSekt White Collection Semi-Dry,84,13.0,Ukraine,NaN,NaN,Anna Lee C. Iijima,NaN,Sparkling Blend,Artemovsk

In [79]:
df[df['province'].isnull()]

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
913,Gotsa Family Wines 2014 Asureti Valley Chinuri,NaN,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Chinuri,Gotsa Family Wines
3131,Barton & Guestier NV Partager Red,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Red Blend,Barton & Guestier
4243,Kakhetia Traditional Winemaking 2012 Red Natur...,NaN,"Violet-red in color, this semisweet wine has a...",Red Naturally Semi-Sweet,88,18.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Ojaleshi,Kakhetia Traditional Winemaking
9509,Tsililis 2015 Theopetra Malagouzia-Assyrtiko W...,NaN,This mouthwatering blend starts with a nose of...,Theopetra Malagouzia-Assyrtiko,92,28.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,White Blend,Tsililis
9750,Ross-idi 2015 Orange Nikolaevo Vineyard Chardo...,NaN,This orange-style wine has a cloudy yellow-gol...,Orange Nikolaevo Vineyard,89,28.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Chardonnay,Ross-idi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
124176,Les Frères Dutruy 2014 Les Romaines Red,NaN,This Swiss red blend is composed of four varie...,Les Romaines,90,30.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Red Blend,Les Frères Dutruy
129407,El Capricho 2015 Reserve Cabernet Sauvignon,NaN,Dry spicy aromas of dusty plum and tomato add ...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,Cabernet Sauvignon,El Capricho
129408,El Capricho 2015 Reserve Tempranillo,NaN,El Capricho is one of Uruguay's more consisten...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,Tempranillo,El Capricho
129590,Büyülübağ 2012 Shah Red,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Red Blend,Büyülübağ
129900,Psagot 2014 Merlot,NaN,This wine offers a delightful bouquet of black...,NaN,91,32.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Merlot,Psagot

In [80]:
df[df['province'].notnull()]

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
0,Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
1,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
2,Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
3,St. Julian 2013 Reserve Late Harvest Riesling ...,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
4,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,Citation 2004 Pinot Noir (Oregon),US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Pinot Noir,Citation
129968,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Gresser
129969,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Pinot Gris,Domaine Marcel Deiss
129970,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Schoffit

##### Summary functions and maps

In [81]:
df.describe()

              points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [82]:
df.describe().T

           count       mean        std   min   25%   50%   75%     max
points  129971.0  88.447138   3.039730  80.0  86.0  88.0  91.0   100.0
price   120975.0  35.363389  41.022218   4.0  17.0  25.0  42.0  3300.0

In [83]:
df.describe(include=['object']).T

,count,unique,top,freq
title,129971,118840,Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma...,11
country,129908,43,US,54504
description,129971,119955,"Seductively tart in lemon pith, cranberry and ...",3
designation,92506,37979,Reserve,2009
province,129908,425,California,36247
region_1,108724,1229,Napa Valley,4480
region_2,50511,17,Central Coast,11065
taster_name,103727,19,Roger Voss,25514
taster_twitter_handle,98758,15,@vossroger,25514
variety,129970,707,Pinot Noir,13272
winery,129971,16757,Wines & Winemakers,222

In [84]:
df[['points', 'price']].corr()

          points     price
points  1.000000  0.416167
price   0.416167  1.000000

In [85]:
print(df['points'].mean())

88.44713820775404

In [86]:
df['taster_name']

0              Kerin O’Keefe
1                 Roger Voss
2               Paul Gregutt
3         Alexander Peartree
4               Paul Gregutt
                 ...
129966    Anna Lee C. Iijima
129967          Paul Gregutt
129968            Roger Voss
129969            Roger Voss
129970            Roger Voss
Name: taster_name, Length: 129971, dtype: object

In [87]:
print('The unique taster names are', df['taster_name'].unique()) #shows all the unique types in column

The unique taster names are ['Kerin O’Keefe' 'Roger Voss' 'Paul Gregutt' 'Alexander Peartree'
 'Michael Schachner' 'Anna Lee C. Iijima' 'Virginie Boone' 'Matt Kettmann'
 nan 'Sean P. Sullivan' 'Jim Gordon' 'Joe Czerwinski'
 'Anne Krebiehl\xa0MW' 'Lauren Buzzeo' 'Mike DeSimone' 'Jeff Jenssen'
 'Susan Kostrzewa' 'Carrie Dykes' 'Fiona Adams' 'Christina Pickard']

In [88]:
print('The number of unique names are', df['taster_name'].nunique()) #shows count of unique values

The number of unique names are 19

In [89]:
df['taster_name'].value_counts()

taster_name
Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne Krebiehl MW       3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: count, dtype: int64

In [90]:
df['taster_name'].value_counts(normalize=True)

taster_name
Roger Voss            0.245973
Michael Schachner     0.145902
Kerin O’Keefe         0.103888
Virginie Boone        0.091943
Paul Gregutt          0.091895
Matt Kettmann         0.061045
Joe Czerwinski        0.049621
Sean P. Sullivan      0.047876
Anna Lee C. Iijima    0.042564
Jim Gordon            0.040269
Anne Krebiehl MW      0.035526
Lauren Buzzeo         0.017691
Susan Kostrzewa       0.010460
Mike DeSimone         0.004955
Jeff Jenssen          0.004734
Alexander Peartree    0.004001
Carrie Dykes          0.001340
Fiona Adams           0.000260
Christina Pickard     0.000058
Name: proportion, dtype: float64

In [91]:
df['taster_name'].value_counts(normalize=True)*100

taster_name
Roger Voss            24.597260
Michael Schachner     14.590222
Kerin O’Keefe         10.388809
Virginie Boone         9.194327
Paul Gregutt           9.189507
Matt Kettmann          6.104486
Joe Czerwinski         4.962064
Sean P. Sullivan       4.787567
Anna Lee C. Iijima     4.256365
Jim Gordon             4.026917
Anne Krebiehl MW       3.552595
Lauren Buzzeo          1.769067
Susan Kostrzewa        1.046015
Mike DeSimone          0.495532
Jeff Jenssen           0.473358
Alexander Peartree     0.400089
Carrie Dykes           0.134006
Fiona Adams            0.026030
Christina Pickard      0.005784
Name: proportion, dtype: float64

In [92]:
df['price_cut']=pd.cut(df['price'], 5)

In [93]:
df['price_cut'].value_counts()

price_cut
(0.704, 663.2]      120926
(663.2, 1322.4]         40
(1981.6, 2640.8]         5
(1322.4, 1981.6]         3
(2640.8, 3300.0]         1
Name: count, dtype: int64

In [94]:
#Delete column in dataFrame

df.drop('price_cut', axis=1, inplace=True)

In [95]:
points_mean=df['points'].mean()

print(points_mean)

88.44713820775404

##### map

In [96]:
df['points'].map(lambda row: row-points_mean)

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

##### Grouping and Sorting

##### Groupwise analysis

In [97]:
df.head()

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
0,Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
1,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
2,Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
3,St. Julian 2013 Reserve Late Harvest Riesling ...,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
4,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks

In [98]:
print(df['points'].max())

100

In [99]:
df.groupby('points')['price'].mean()

points
80      16.372152
81      17.182353
82      18.870767
83      18.237353
84      19.310215
85      19.949562
86      22.133759
87      24.901884
88      28.687523
89      32.169640
90      36.906622
91      43.224252
92      51.037763
93      63.112216
94      81.436938
95     109.235420
96     159.292531
97     207.173913
98     245.492754
99     284.214286
100    485.947368
Name: price, dtype: float64

In [100]:
df.groupby('points')['price'].agg(['max', 'min'])

           max   min
points
80        69.0   5.0
81       130.0   5.0
82       150.0   4.0
83       225.0   4.0
84       225.0   4.0
85       320.0   4.0
86       170.0   4.0
87       800.0   5.0
88      3300.0   6.0
89       500.0   7.0
90       510.0   8.0
91      2013.0   7.0
92       750.0  11.0
93       770.0  12.0
94      1125.0  13.0
95       973.0  20.0
96      2500.0  20.0
97      2000.0  35.0
98      1900.0  50.0
99       850.0  44.0
100     1500.0  80.0

In [101]:
df.groupby('points')['price'].agg(['max', min])

           max   min
points
80        69.0   5.0
81       130.0   5.0
82       150.0   4.0
83       225.0   4.0
84       225.0   4.0
85       320.0   4.0
86       170.0   4.0
87       800.0   5.0
88      3300.0   6.0
89       500.0   7.0
90       510.0   8.0
91      2013.0   7.0
92       750.0  11.0
93       770.0  12.0
94      1125.0  13.0
95       973.0  20.0
96      2500.0  20.0
97      2000.0  35.0
98      1900.0  50.0
99       850.0  44.0
100     1500.0  80.0

##### Sorting

In [102]:
df.sort_values('price')

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
20484,Dancing Coyote 2015 White (Clarksburg),US,"Fruity, soft and rather sweet, this wine smell...",NaN,85,4.0,California,Clarksburg,Central Valley,Jim Gordon,@gordone_cellars,White Blend,Dancing Coyote
112919,Terrenal 2010 Estate Bottled Tempranillo (Yecla),Spain,"Nice on the nose, this has a leafy note and a ...",Estate Bottled,84,4.0,Levante,Yecla,NaN,Michael Schachner,@wineschach,Tempranillo,Terrenal
59507,Pam's Cuties NV Unoaked Chardonnay (California),US,"Sweet and fruity, this canned wine feels soft ...",Unoaked,83,4.0,California,California,California Other,Jim Gordon,@gordone_cellars,Chardonnay,Pam's Cuties
31530,Bandit NV Chardonnay (California),US,"Packaged in a cute yellow recyclable Tetrapak,...",NaN,84,4.0,California,California,California Other,NaN,NaN,Chardonnay,Bandit
61768,Terrenal 2010 Cabernet Sauvignon (Yecla),Spain,This opens with standard cherry and berry arom...,NaN,84,4.0,Levante,Yecla,NaN,Michael Schachner,@wineschach,Cabernet Sauvignon,Terrenal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129844,Caparzo 2006 Doga delle Clavule (Morellino di...,Italy,"Doga delle Clavule is a neutral, mineral-drive...",Doga delle Clavule,86,NaN,Tuscany,Morellino di Scansano,NaN,NaN,NaN,Sangiovese,Caparzo
129860,Quinta da Pacheca 2013 Pacheca Superior Red (D...,Portugal,This rich wine has a firm structure as well as...,Pacheca Superior,90,NaN,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta da Pacheca
129863,Seacampo 2011 Reserva Red (Dão),Portugal,This mature wine that has 50% Touriga Nacional...,Reserva,90,NaN,Dão,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Seacampo
129893,Le Mandolare 2015 Corte Menini (Soave Classico),Italy,"Aromas of passion fruit, hay and a vegetal not...",Corte Menini,91,NaN,Veneto,Soave Classico,NaN,Kerin O’Keefe,@kerinokeefe,Garganega,Le Mandolare
129964,Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...,France,"Initially quite muted, this wine slowly develo...",Domaine Saint-Rémy Herrenweg,90,NaN,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Ehrhart

In [103]:
df.sort_values('price', ascending=True)

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
20484,Dancing Coyote 2015 White (Clarksburg),US,"Fruity, soft and rather sweet, this wine smell...",NaN,85,4.0,California,Clarksburg,Central Valley,Jim Gordon,@gordone_cellars,White Blend,Dancing Coyote
112919,Terrenal 2010 Estate Bottled Tempranillo (Yecla),Spain,"Nice on the nose, this has a leafy note and a ...",Estate Bottled,84,4.0,Levante,Yecla,NaN,Michael Schachner,@wineschach,Tempranillo,Terrenal
59507,Pam's Cuties NV Unoaked Chardonnay (California),US,"Sweet and fruity, this canned wine feels soft ...",Unoaked,83,4.0,California,California,California Other,Jim Gordon,@gordone_cellars,Chardonnay,Pam's Cuties
31530,Bandit NV Chardonnay (California),US,"Packaged in a cute yellow recyclable Tetrapak,...",NaN,84,4.0,California,California,California Other,NaN,NaN,Chardonnay,Bandit
61768,Terrenal 2010 Cabernet Sauvignon (Yecla),Spain,This opens with standard cherry and berry arom...,NaN,84,4.0,Levante,Yecla,NaN,Michael Schachner,@wineschach,Cabernet Sauvignon,Terrenal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129844,Caparzo 2006 Doga delle Clavule (Morellino di...,Italy,"Doga delle Clavule is a neutral, mineral-drive...",Doga delle Clavule,86,NaN,Tuscany,Morellino di Scansano,NaN,NaN,NaN,Sangiovese,Caparzo
129860,Quinta da Pacheca 2013 Pacheca Superior Red (D...,Portugal,This rich wine has a firm structure as well as...,Pacheca Superior,90,NaN,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta da Pacheca
129863,Seacampo 2011 Reserva Red (Dão),Portugal,This mature wine that has 50% Touriga Nacional...,Reserva,90,NaN,Dão,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Seacampo
129893,Le Mandolare 2015 Corte Menini (Soave Classico),Italy,"Aromas of passion fruit, hay and a vegetal not...",Corte Menini,91,NaN,Veneto,Soave Classico,NaN,Kerin O’Keefe,@kerinokeefe,Garganega,Le Mandolare
129964,Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...,France,"Initially quite muted, this wine slowly develo...",Domaine Saint-Rémy Herrenweg,90,NaN,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Ehrhart

In [104]:
df.sort_values('price', ascending=False)

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
80290,Château les Ormes Sorbet 2013 Médoc,France,This ripe wine shows plenty of blackberry frui...,NaN,88,3300.0,Bordeaux,Médoc,NaN,Roger Voss,@vossroger,Bordeaux-style Red Blend,Château les Ormes Sorbet
15840,Château Pétrus 2014 Pomerol,France,The wine is a velvet glove in an iron fist. Th...,NaN,96,2500.0,Bordeaux,Pomerol,NaN,Roger Voss,@vossroger,Bordeaux-style Red Blend,Château Pétrus
98380,Domaine du Comte Liger-Belair 2010 La Romanée,France,"A superb wine from a great year, this is power...",NaN,96,2500.0,Burgundy,La Romanée,NaN,Roger Voss,@vossroger,Pinot Noir,Domaine du Comte Liger-Belair
120391,Blair 2013 Roger Rose Vineyard Chardonnay (Arr...,US,The nose on this single-vineyard wine from a s...,Roger Rose Vineyard,91,2013.0,California,Arroyo Seco,Central Coast,Matt Kettmann,@mattkettmann,Chardonnay,Blair
113564,Domaine du Comte Liger-Belair 2005 La Romanée,France,"A wonderfully complete wine, with all the elem...",NaN,96,2000.0,Burgundy,La Romanée,NaN,Roger Voss,@vossroger,Pinot Noir,Domaine du Comte Liger-Belair
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129844,Caparzo 2006 Doga delle Clavule (Morellino di...,Italy,"Doga delle Clavule is a neutral, mineral-drive...",Doga delle Clavule,86,NaN,Tuscany,Morellino di Scansano,NaN,NaN,NaN,Sangiovese,Caparzo
129860,Quinta da Pacheca 2013 Pacheca Superior Red (D...,Portugal,This rich wine has a firm structure as well as...,Pacheca Superior,90,NaN,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta da Pacheca
129863,Seacampo 2011 Reserva Red (Dão),Portugal,This mature wine that has 50% Touriga Nacional...,Reserva,90,NaN,Dão,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Seacampo
129893,Le Mandolare 2015 Corte Menini (Soave Classico),Italy,"Aromas of passion fruit, hay and a vegetal not...",Corte Menini,91,NaN,Veneto,Soave Classico,NaN,Kerin O’Keefe,@kerinokeefe,Garganega,Le Mandolare
129964,Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...,France,"Initially quite muted, this wine slowly develo...",Domaine Saint-Rémy Herrenweg,90,NaN,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Ehrhart

In [105]:
df.sort_values(['price', 'country'], ascending=[False, False])

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
80290,Château les Ormes Sorbet 2013 Médoc,France,This ripe wine shows plenty of blackberry frui...,NaN,88,3300.0,Bordeaux,Médoc,NaN,Roger Voss,@vossroger,Bordeaux-style Red Blend,Château les Ormes Sorbet
15840,Château Pétrus 2014 Pomerol,France,The wine is a velvet glove in an iron fist. Th...,NaN,96,2500.0,Bordeaux,Pomerol,NaN,Roger Voss,@vossroger,Bordeaux-style Red Blend,Château Pétrus
98380,Domaine du Comte Liger-Belair 2010 La Romanée,France,"A superb wine from a great year, this is power...",NaN,96,2500.0,Burgundy,La Romanée,NaN,Roger Voss,@vossroger,Pinot Noir,Domaine du Comte Liger-Belair
120391,Blair 2013 Roger Rose Vineyard Chardonnay (Arr...,US,The nose on this single-vineyard wine from a s...,Roger Rose Vineyard,91,2013.0,California,Arroyo Seco,Central Coast,Matt Kettmann,@mattkettmann,Chardonnay,Blair
65352,Château Pétrus 2011 Pomerol,France,This extravagantly perfumed wine has great jui...,NaN,97,2000.0,Bordeaux,Pomerol,NaN,Roger Voss,@vossroger,Bordeaux-style Red Blend,Château Pétrus
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129388,Antigal 2006 Aduentus Classic Red (Mendoza),Argentina,"Slightly tart and like rhubarb at first, but i...",Aduentus Classic,85,NaN,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Red Blend,Antigal
3131,Barton & Guestier NV Partager Red,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Red Blend,Barton & Guestier
11348,Barton & Guestier NV Partager White,NaN,"Light and fruity, this is a wine that has some...",Partager,82,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,White Blend,Barton & Guestier
16749,Bartho Eksteen 2016 Cape Winemakers Guild Vloe...,NaN,Winemaker: Bartho Eksteen. This wooded Sauvy s...,Cape Winemakers Guild Vloekskoot Wooded,91,NaN,NaN,NaN,NaN,Lauren Buzzeo,@laurbuzz,Sauvignon Blanc,Bartho Eksteen
57612,Newton Johnson 2016 Cape Winemakers Guild Wind...,NaN,Winemaker: Gordon Newton Johnson. This is such...,Cape Winemakers Guild Windansea,92,NaN,NaN,NaN,NaN,Lauren Buzzeo,@laurbuzz,Pinot Noir,Newton Johnson

In [106]:
df.head()

,title,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
0,Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
1,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
2,Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
3,St. Julian 2013 Reserve Late Harvest Riesling ...,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
4,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks

##### Text methods

In [107]:
df['taster_name'].str.lower()

0              kerin o’keefe
1                 roger voss
2               paul gregutt
3         alexander peartree
4               paul gregutt
                 ...
129966    anna lee c. iijima
129967          paul gregutt
129968            roger voss
129969            roger voss
129970            roger voss
Name: taster_name, Length: 129971, dtype: object

In [108]:
df.taster_name.str.contains("eri")

0          True
1         False
2         False
3         False
4         False
          ...
129966    False
129967    False
129968    False
129969    False
129970    False
Name: taster_name, Length: 129971, dtype: object

##### Apply function on Dataframe

In [109]:
df._get_numeric_data()

        points  price
0           87    NaN
1           87   15.0
2           87   14.0
3           87   13.0
4           87   65.0
...        ...    ...
129966      90   28.0
129967      90   75.0
129968      90   30.0
129969      90   32.0
129970      90   21.0

[129971 rows x 2 columns]

In [110]:
num_cols=df._get_numeric_data().columns

print(num_cols)

Index(['points', 'price'], dtype='object')

In [111]:
df[num_cols].apply(np.max)

points     100.0
price     3300.0
dtype: float64

##### date time

In [112]:
data = pd.DataFrame({'year': [1997, 1998],
                   'month': [12, 9],
                   'day': [3, 27]})

In [113]:
data

   year  month  day
0  1997     12    3
1  1998      9   27

In [114]:
pd.to_datetime(data)

0   1997-12-03
1   1998-09-27
dtype: datetime64[ns]

In [115]:
pd.to_datetime('1997-3-12 12:00:00.0000000011', format='%Y-%m-%d %H:%M:%S.%f')

Timestamp('1997-03-12 12:00:00.000000001')

##### Pivot tabels

In [116]:
# Create a DataFrame
data = pd.DataFrame({'name' : ['Ul', 'Sr', 'Sr', 'Gun', 'Ul'],
                  'subject': ['Python', 'SQL', 'SPSS','SQL','SQL'],
                   'score': [100, 65, 95, 95, 80],
                   })

In [117]:
data

  name subject  score
0   Ul  Python    100
1   Sr     SQL     65
2   Sr    SPSS     95
3  Gun     SQL     95
4   Ul     SQL     80

In [118]:
data.pivot(index='name', columns='subject', values=['score'])

         score
subject Python  SPSS   SQL
name
Gun        NaN   NaN  95.0
Sr         NaN  95.0  65.0
Ul       100.0   NaN  80.0

In [119]:
data.pivot_table(index='subject', values=['score'], aggfunc={'score': np.max})

         score
subject
Python     100
SPSS        95
SQL         95

##### HTML tables

In [120]:
data = pd.read_html('https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population')

In [121]:
res=data[0].head()

In [122]:
res.head()

,Unnamed: 0,Country / Dependency,Population,% of world,Date,Source (official or from the United Nations),Unnamed: 6
0,–,World,8084406000,100%,20 Jan 2024,UN projection[3],NaN
1,1,China,1409670000,NaN,31 Dec 2023,Official estimate[4],[b]
2,2,India,1392329000,NaN,1 Mar 2023,Official projection[5],[c]
3,3,United States,335893238,NaN,1 Jan 2024,Official estimate[7],[d]
4,4,Indonesia,279118866,NaN,1 Jul 2023,National annual projection[8],NaN

##### concatenation and merge

In [123]:
# creating the Series
series1 = pd.Series([12, 3, 27])

series2 = pd.Series(['U', 'Q', 'N'])

In [124]:
pd.concat([series1, series2], axis = 0)

0    12
1     3
2    27
0     U
1     Q
2     N
dtype: object

In [125]:
pd.concat([series1, series2], axis = 1)

    0  1
0  12  U
1   3  Q
2  27  N

In [126]:
pd.concat([series1, series2], axis = 1, keys=['col1', 'col2'])

   col1 col2
0    12    U
1     3    Q
2    27    N

In [127]:
df1=pd.DataFrame({'number': [12, 24, 27, 10, 4],
                 'name':['Ul', 'En', 'Sr', 'Gun', 'Ay']
                 })

df2=pd.DataFrame({'number':[12, 10, 24, 27, 10, 12, 3],
                 'subject':['SQL', 'Python', 'Algebra', 'SQL', 'SQL', 'Python', 'C'],
                  'grade':[100, 90, 12, 45, 65, 95, 85]
                 })

In [128]:
df1

   number name
0      12   Ul
1      24   En
2      27   Sr
3      10  Gun
4       4   Ay

In [129]:
df2

   number  subject  grade
0      12      SQL    100
1      10   Python     90
2      24  Algebra     12
3      27      SQL     45
4      10      SQL     65
5      12   Python     95
6       3        C     85

In [130]:
df1.merge(df2, how='inner', on='number')

   number name  subject  grade
0      12   Ul      SQL    100
1      12   Ul   Python     95
2      24   En  Algebra     12
3      27   Sr      SQL     45
4      10  Gun   Python     90
5      10  Gun      SQL     65

In [131]:
df1.merge(df2, how='left', on='number')

   number name  subject  grade
0      12   Ul      SQL  100.0
1      12   Ul   Python   95.0
2      24   En  Algebra   12.0
3      27   Sr      SQL   45.0
4      10  Gun   Python   90.0
5      10  Gun      SQL   65.0
6       4   Ay      NaN    NaN

In [132]:
df1.merge(df2, how='outer', on='number')

   number name  subject  grade
0      12   Ul      SQL  100.0
1      12   Ul   Python   95.0
2      24   En  Algebra   12.0
3      27   Sr      SQL   45.0
4      10  Gun   Python   90.0
5      10  Gun      SQL   65.0
6       4   Ay      NaN    NaN
7       3  NaN        C   85.0

In [133]:
df1.merge(df2, left_on='number', right_on='grade')

   number_x name  number_y  subject  grade
0        12   Ul        24  Algebra     12

As you can see, the fact that the result is obtained does not mean that the query written is correct.